# Using SDSS-V Targeting Flags with `semaphore`

## Learning Goals
By the end of this tutorial, you will:
- How to select spectra by their targeting information
- How to get the targeting information of a specific target

## Introduction
The SDSS-V Survey uses a complex targeting schema, where targets are selected through many cartons associated with the different SDSS-V mappers and programs. 

In this short tutorial, we will briefly cover determining which targets in a summary file are associated with a particular carton, program, or master. It also describes how to determine the targeting information for a single source. 

## Imports

This tutorial requires two commonly used python packages and two SDSS specific packages
- numpy for filtering of arrays
- astropy for reading fits tables
- sdss-access for accessing data on the SAS
- semaphore for exploring the flags

Missing packages can be installed via `pip install numpy astropy sdss-access sdss-semaphore==0.2.4`


NOTE: You may want to set the `$SAS_BASE_DIR` environment variable before starting this notebook, other wise `$HOME/sas` will be created and used



In [1]:
import numpy as np
from astropy.io import fits
from sdss_access import Access
from sdss_semaphore.targeting import TargetingFlags

# setup sdss_access for DR19
access = Access(release='DR19')

## Load the Data
We will use `sdss-access` to find/download the file. `sdss-access` has extensive documentation, but we should mention a few things. First, if you are a member of the collaboration accessing proprietary data, you need to set up a .netrc file. After that usage is the same for everyone. For public data, no .netrc file is needed.

You need specify the file species you need, in this case 'mwmAllVisit', then a series of keyword arguments that vary depending on the file species. A list of file species and their keyword arugments is available.

The code below show an example of retreiving a summary file. access.full() builds the file path, access.exists() checks if the file exists, and access.commit() will retrieve the file and save it to your local SAS (`$SAS_BASE_DIR`) with the same structure as the SAS (so it will be many files deep).

In [2]:
filename = access.full('mwmAllVisit',v_astra = '0.6.0')
if not access.exists('',full=filename):
    # if the file does not exist locally, this code will download the data.
    access.remote()
    access.add('mwmAllVisit',v_astra = '0.6.0')
    access.set_stream()
    access.commit()
print(filename)


/uufs/chpc.utah.edu/common/home/sdss50/ipl-3/spectro/astra/0.6.0/summary/mwmAllVisit-0.6.0.fits.gz


### Open the file
Now use `astropy.fitsio` to load the data
- HDU 1 contains the BOSS Spectra
- HDU 2 contains the APOGEE Spectra

In [3]:
hdul = fits.open(filename)
hdul[0].header
boss_data = hdul[1].data

### Converting the stored column to a set of Targeting Flags
Now use the semaphore package to convert the fits column to Targeting Flags

In [4]:
flags = TargetingFlags(boss_data["SDSS5_TARGET_FLAGS"])

In [5]:
# Let's count the number of targets assigned to each carton (and skip empty cartons)
for label, count in flags.count(skip_empty=True).items():
    print(f"{label}: {count}")

mwm_snc_100pc_0.1.0: 38190
mwm_snc_250pc_0.1.0: 2019
mwm_cb_300pc_0.1.0: 123
mwm_cb_cvcandidates_0.1.0: 971
mwm_halo_sm_0.1.0: 2589
mwm_halo_bb_0.1.0: 32694
mwm_yso_s1_0.1.0: 13798
mwm_yso_s2_0.1.0: 44
mwm_yso_s2-5_0.1.0: 8
mwm_yso_s3_0.1.0: 22710
mwm_yso_ob_0.1.0: 16
mwm_yso_cmz_0.1.0: 1
mwm_yso_cluster_0.1.0: 20272
mwm_rv_long-fps_0.1.0: 2597
mwm_rv_long-bplates_0.1.0: 586
mwm_ob_cepheids_0.1.0: 267
mwm_rv_short-fps_0.1.0: 8429
mwm_rv_short-bplates_0.1.0: 847
mwm_ob_core_0.1.0: 147242
mwm_rv_short-rm_0.1.0: 153
mwm_rv_long-rm_0.1.0: 53
ops_std_boss_0.1.0: 150693
mwm_wd_core_0.1.0: 40413
mwm_gg_core_0.1.0: 8571
mwm_planet_tess_0.1.0: 5090
bhm_aqmes_med_0.1.0: 1691
mwm_cb_gaiagalex_0.1.0: 46436
bhm_aqmes_med-faint_0.1.0: 3354
mwm_tessrgb_core_0.1.0: 4772
bhm_aqmes_wide3_0.1.0: 1718
bhm_aqmes_wide3-faint_0.1.0: 2550
bhm_aqmes_wide2_0.1.0: 1116
bhm_aqmes_wide2-faint_0.1.0: 742
bhm_aqmes_bonus-dark_0.1.0: 17438
bhm_aqmes_bonus-bright_0.1.0: 1713
bhm_csc_boss-dark_0.1.0: 40476
bhm_csc_boss

# Flags have attributes

The counts above are for targets assigned to a specific carton, with a specific version. Sometimes we don't care about the carton version and we just want to count by the effective number of targets assigned to that carton (over all versions), or we might want to count by the number of targets assigned to each mapper, or some other attribute.

The `TargetingFlags.mapping` attribute contains a reference dictionary for all cartons, including their attributes. Here's how we can count targets by those attributes:


In [6]:
for mapper, count in flags.count_by_attribute("mapper").items():
    print(f"{mapper}: {count:,}")

mwm: 577,505
ops: 396,005
bhm: 73,516
open: 450,749


In [7]:
for program, count in flags.count_by_attribute("program").items():
    print(f"{program}: {count:,}")

mwm_snc: 149,314
mwm_cb: 91,007
mwm_halo: 85,511
mwm_yso: 86,540
mwm_rv: 11,548
mwm_ob: 148,043
ops_std: 351,759
mwm_wd: 42,128
mwm_gg: 8,571
mwm_planet: 11,137
bhm_aqmes: 4,346
bhm_filler: 43,243
mwm_tessrgb: 8,521
bhm_csc: 55,637
ops_sky: 0
bhm_rm: 31,079
bhm_spiders: 18,851
mwm_dust: 82
mwm_legacy: 28,031
mwm_galactic: 9,746
mwm_filler: 54,536
mwm_tess_ob: 0
mwm_erosita: 16,380
open_fiber: 450,749
commissioning: 59,120
SKY: 0
mwm_tessob: 0
mwm_magcloud: 1,558
mwm_bin: 15,571
mwm_validation: 2,553
mwm_monitor: 22


# I own a carton. Where are my spectra?

You can efficiently construct boolean masks to select spectra that are assigned to a carton, program, mapper, or any other attribute.

The easiest way to do this is with the following methods:
- `TargetingFlags.in_carton_pk`: If you know the database primary key (`targetdb.carton.pk`) of your carton
- `TargetingFlags.in_carton_name`: If you know the name of your carton.
- `TargetingFlags.in_carton_label`: If you know the name and version (name_ver) of your carton
- `TargetingFlags.in_mapper`: To select by mapper (e.g., BHM, MWM)
- `TargetingFlags.in_program`: To select by program name.
- `TargetingFlags.in_alt_name`: To select by alternative name, curated with thanks by Marina Koukel.
- `TargetingFlags.in_alt_program`: To select by alternative program name, curated with thanks by Marina Koukel.

If you're not sure what your carton's alternative name or program is, you might find these properties useful:

- `TargetingFlags.all_mappers`: a tuple of all unique mapper names;
- `TargetingFlags.all_programs`: a tuple of all unique program names;
- `TargetingFlags.all_carton_names`: a tuple of all unique carton names;
- `TargetingFlags.all_alt_carton_names`: a tuple of all unique alternative names;
- `TargetingFlags.all_alt_programs`: a tuple of all unique alternative program names;

or you can look this up from `TargetingFlags.mapping`.

In [8]:
print("Mappers:")
for mapper in flags.all_mappers:
    print(f"\t{mapper}")
    
print("Programs")
for program in flags.all_programs:
    print(f"\t{program}")

print("Cartons names")
for name in flags.all_carton_names:
    print(f"\t{name}")

print("Alternative cartons names")
for alt_name in flags.all_alt_carton_names:
    print(f"\t{alt_name}")

print("Alternative programs")
for alt_program in flags.all_alt_programs:
    print(f"\t{alt_program}")


Mappers:
	ops
	bhm
	open
	mwm
Programs
	ops_std
	mwm_wd
	mwm_galactic
	mwm_monitor
	mwm_filler
	mwm_cb
	open_fiber
	mwm_planet
	mwm_dust
	mwm_tessrgb
	bhm_csc
	mwm_legacy
	bhm_aqmes
	mwm_validation
	mwm_yso
	mwm_tess_ob
	bhm_filler
	bhm_rm
	mwm_magcloud
	mwm_halo
	mwm_snc
	mwm_erosita
	SKY
	commissioning
	mwm_tessob
	ops_sky
	bhm_spiders
	mwm_ob
	mwm_bin
	mwm_gg
	mwm_rv
Cartons names
	bhm_colr_galaxies_lsdr10
	mwm_halo_nmp_xp_apogee
	mwm_yso_disk_boss_single
	manual_fps_position_stars
	mwm_rv_long-fps
	mwm_cb_galex_mag_boss
	mwm_yso_variable_boss
	manual_mwm_halo_vmp_wise_apogee
	mwm_halo_nmp_xp_boss_single
	mwm_halo_local_high_apogee
	mwm_halo_nmp_xp_boss
	bhm_spiders_agn_skymapperdr2
	manual_bright_targets_g13_offset_fixed_3
	mwm_halo_local_low_apogee
	openfibertargets_nov2020_6c
	manual_mwm_halo_mp_wise_apogee_single
	bhm_colr_galaxies_lsdr8
	ops_std_boss_red
	mwm_yso_ob
	mwm_erosita_stars_boss
	manual_mwm_planet_transiting_bd_apogee
	openfibertargets_nov2020_9
	mwm_halo_local_low_b

### Select by Mapper
If you want to check which rows are in a particular mapper

In [9]:
# Select things assigned to MWM
mwm_mask = flags.in_mapper("mwm")
mwm_mask

array([ True, False,  True, ..., False,  True, False])

In [10]:
print(f"There are {np.sum(flags.in_mapper('mwm')):,} things assigned to MWM")

There are 577,505 things assigned to MWM


### Select by Program
If you want to check which rows are in a particular program

In [11]:
flags.in_program("mwm_wd")

array([False, False,  True, ..., False, False, False])

### Select by name
If you want to check which rows are in a particular carton

In [12]:
flags.in_carton_name("mwm_snc_250pc")

array([False, False, False, ..., False, False, False])

## I have a target, how was it targeted?

If you have a CATALOGID or SDSS_ID and would like to know the targeting cartons for that source

In [13]:
catalogid = 27021598754184543
idx = np.where((boss_data["CATALOGID21"] == catalogid) |
               (boss_data["CATALOGID25"] == catalogid) | 
               (boss_data["CATALOGID31"] == catalogid))[0]
flag1 = TargetingFlags(boss_data["SDSS5_TARGET_FLAGS"][idx])
for label, count in flag1.count(skip_empty=True).items():
    print(f"{label}")

mwm_yso_s3_0.1.0
mwm_yso_cluster_0.1.0
mwm_yso_variable_apogee_0.5.0
mwm_yso_variable_boss_0.5.0
mwm_yso_cluster_apogee_0.5.0
mwm_yso_cluster_boss_0.5.0
mwm_yso_cluster_apogee_0.5.17
mwm_yso_cluster_boss_0.5.17
mwm_yso_variable_apogee_0.5.17
mwm_yso_variable_boss_0.5.17
mwm_yso_cluster_apogee_1.0.6
mwm_yso_cluster_boss_1.0.6
mwm_yso_variable_apogee_1.0.6
mwm_yso_variable_boss_1.0.6
mwm_yso_variable_apogee_single_1.0.33
mwm_yso_variable_boss_single_1.0.33
mwm_yso_cluster_apogee_single_1.0.33
mwm_yso_cluster_boss_single_1.0.33


In [14]:
sdss_id = 87406300
idx = np.where(boss_data["SDSS_ID"] == sdss_id)[0]
flag1 = TargetingFlags(boss_data["SDSS5_TARGET_FLAGS"][idx])
for label, count in flag1.count(skip_empty=True).items():
    print(f"{label}")

mwm_yso_s3_0.1.0
mwm_yso_cluster_0.1.0
mwm_yso_variable_apogee_0.5.0
mwm_yso_variable_boss_0.5.0
mwm_yso_cluster_apogee_0.5.0
mwm_yso_cluster_boss_0.5.0
mwm_yso_cluster_apogee_0.5.17
mwm_yso_cluster_boss_0.5.17
mwm_yso_variable_apogee_0.5.17
mwm_yso_variable_boss_0.5.17
mwm_yso_cluster_apogee_1.0.6
mwm_yso_cluster_boss_1.0.6
mwm_yso_variable_apogee_1.0.6
mwm_yso_variable_boss_1.0.6
mwm_yso_variable_apogee_single_1.0.33
mwm_yso_variable_boss_single_1.0.33
mwm_yso_cluster_apogee_single_1.0.33
mwm_yso_cluster_boss_single_1.0.33


## About this notebook

This notebook was created to give an example of using the `semaphore` tool with the mwmAllVisit file

**Authors**: Andy Casey (andrew.casey@monash.edu), Sean Morrison

**Last Update**: 2024 December 3

If you use `astropy`  for published research, please cite the
authors. Follow this link for more information about citing `astropy`:

* [Citing `astropy`](https://www.astropy.org/acknowledging.html)

And of course please [cite](https://sdss.org/collaboration/citing-sdss/) SDSS when you use our data.